pipeline{
    options{timestamps()}

    agent none
    stages{
        stage('Check scm'){
            agent any
            steps{
                checkout scm
            }
        }
        stage('Build'){
            steps{
                echo "Building...${BUILD_NUMBER}"
                echo "Building completed"
            }
        }
        stage('Test'){
            agent { 
                docker {
                    image 'alpine'
                    args '-u=root'
                }
            }
            steps {
                sh 'apk add --update python3 py3-pip'
                sh 'pip install xmlrunner'
                sh "python3 \${WORKSPACE}/Lab3/test_good.py"
            }
            post {
                always {
                    junit 'test-reports/*.xml'
                }
                success {
                    echo "Application tested successfully completed"
                }
                failure {
                    echo "Something went wrong!"
                }
            }
        }
    }
}