pipeline{
    options{timestamps()}

    agent any
    stages{
        stage('Check scm'){
            agent any
            steps{
                checkout scm
            }
        }
        stage('Build'){
            steps{
                echo "Building...${BUILD_NUMBER}"
                echo "Building completed"
                
            }
        }
        stage('Test'){
            agent { 
                docker {
                    image 'alpine'
                    args '-u=root'
                }
            }
            steps {
                sh 'apk add --update python3 py3-pip'
                sh 'pip install xmlrunner'
                sh "python3 \${WORKSPACE}/Lab3/test_good.py"
                
            }
            post {
                always {
                    junit 'test-reports/*.xml'
                }
                success {
                    echo "Application tested successfully completed"
                }
                failure {
                    echo "Something went wrong!"
                }
            }
            
        }
        stage('Docker Build'){
            steps {
                sh 'pwd'
                sh 'docker build -t lab3 /var/jenkins_home/workspace/Lab3/Lab3'
                // sh 'docker run lab3 test'
            }

        }
        stage('Build Docker Image Info') {
            steps {
                script {
                    // Отримати хеш коміту для тегу образу
                    def commitHash = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
                    // Створити тег образу
                    def imageTag = "lab3:${commitHash}"
                    // Записати тег образу у файл
                    writeFile file: 'docker-image-tag', text: imageTag
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    def imageTag = readFile 'docker-image-tag'
                    // Створити Docker образ та позначити його тегом
                    sh "docker build -t ${imageTag} /var/jenkins_home/workspace/Lab3/Lab3"
                }
            }
        }
        stage('Docker Hub Login') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', passwordVariable: 'DOCKER_HUB_PASSWORD', usernameVariable: 'DOCKER_HUB_USERNAME')]) {
                        sh "docker login --username=${DOCKER_HUB_USERNAME} --password=${DOCKER_HUB_PASSWORD}"
                        def imageTag = readFile 'docker-image-tag'
                        // Надіслати Docker образ на Docker Hub
                        sh "docker push ageevprunich/jenkins_${imageTag}"
                    }
                }
            }
        }
        // stage('Push Docker Image') {
        //     steps {
        //         script {
        //             def imageTag = readFile 'docker-image-tag'
        //             // Надіслати Docker образ на Docker Hub
        //             sh "docker push ${imageTag}"
        //             // sh "docker push ageevprunich/jenkins_lab3:tagname"
        //         }
        //     }
        // }
    }
}